config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :jobs
  resources :applicant_profiles
  resources :applies
  resources :head_profiles
 
  resources :proposals do
    resources :comments
  end
  
  resources :head_proposals do
    resources :head_comments
  end

  resources :control_users

end

app/models/applicant_profile.rb
class ApplicantProfile < ApplicationRecord
    validates :name, presence: { message: ': Não pode ficar em branco' }
    validates :social_name, presence: { message: ': Não pode ficar em branco' }
    validates :date_of_birth, presence: { message: ': Não pode ficar em branco' }
    validates :education, presence: { message: ': Não pode ficar em branco' }
    validates :applicant_description, presence: { message: ': Não pode ficar em branco' }
    validates :experience, presence: { message: ': Não pode ficar em branco' }
    validate :date_of_birth_equal_today        

    def date_of_birth_equal_today
                
        if date_of_birth == Date.current
          errors.add(:date_of_birth, 'deve ser menor que a data de hoje.')
        end
    end
    
end
  

app/controllers/applicant_profiles_controller.rb
class ApplicantProfilesController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @users = User.all
      @head_comments = HeadComment.all
      @head_proposals = HeadProposal.all
      @applicant_profiles = ApplicantProfile.all
    end

    def show
      @applicant_profile = ApplicantProfile.find(params[:id])
    end

    def new
      @applicant_profile = ApplicantProfile.new
    end

    def create
      @applicant_profile = ApplicantProfile.new(applicant_profile_params)
            
      if @applicant_profile.save
         redirect_to @applicant_profile
      else
         flash.now[:alert] = 'Favor preencher todos os campos'  
         render :new 
      end
    end

    def edit
      @applicant_profile = ApplicantProfile.find(params[:id])
    end  

    def update
      @applicant_profile = ApplicantProfile.find(params[:id])
      @applicant_profile.update(applicant_profile_params)
      redirect_to @applicant_profile
    end

    def destroy
      applicant_profile = ApplicantProfile.find(params[:id]) 
      applicant_profile.destroy 
      redirect_to root_path
    end

    private

    def applicant_profile_params
      params.require(:applicant_profile).permit(:name, :social_name, :date_of_birth,
                                                :education, :applicant_description,
                                                :experience)
    end
end

app/views/applicant_profiles/_form.html.erb
<% if @applicant_profile.errors.any? %>
    <p>Favor corrigir os seguintes erros</p>
    <ul>
    <% @applicant_profile.errors.full_messages.each do |message| %>
      <p><li><%= message %></li></p>
    <% end %>
    </ul>
<% end %>

<%= form_for applicant_profile do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :social_name, 'Nome social' %>
      <%= f.text_field :social_name %>
    </div>
    <div class="form-group">
      <%= f.label :date_of_birth, 'Data de aniversário' %>
      <%= f.date_field :date_of_birth %>
    </div>
    <div class="form-group">
      <%= f.label :education, 'Educação' %>
      <%= f.text_field :education %>
    </div>
    <div class="form-group">
      <%= f.label :applicant_description, 'Descrição' %>
      <%= f.text_field :applicant_description %>
    </div> 
    <div class="form-group">
      <%= f.label :experience, 'Experiência' %>
      <%= f.text_field :experience %>
    </div> 
    <%= f.submit 'Enviar' %>
<% end %>  

app/views/applicant_profiles/edit.html.erb
<h1>Editar inscrição</h1>

<%= render partial: 'form', locals: { applicant_profile: @applicant_profile } %>
<p><%= link_to 'Voltar', applicant_profile_path %></p>

app/views/applicant_profiles/index.html.erb
<% if current_user.email == 'applicant@applicant.com' %>

    <h1>Painel de acesso</h1>

    <% if @applicant_profiles.empty? %>
        <p>Perfil ainda não cadastrado.</p>
        <p>Para ter acesso às vagas, favor cadastrar perfil.</p>
        <p><%= link_to 'Criar perfil', new_applicant_profile_path %></p>
    <% else %>
        <p><%= link_to 'Vagas', new_apply_path %></p>
        <p><%= link_to 'Inscrições efetuadas', applies_path%></p>
        
        <p><%= link_to 'Fazer proposta', proposals_path%></p>
        <p><%= link_to 'Responder proposta/comentário', proposals_path%></p>

    <p><h2>Perfil</h2></p>
    
    <% @applicant_profiles.each do |applicant_profile| %>
        <p>Nome: <%= applicant_profile.name %></p>
        <p>Nome social: <%= applicant_profile.social_name %></p>
        <p>Data de aniversário: <%= applicant_profile.date_of_birth %></p>
        <p>Educação: <%= applicant_profile.education %></p>
        <p>Descrição do candidato: <%= applicant_profile.applicant_description %></p>
        <p>Experiência: <%= applicant_profile.experience %></p>
        
        <p><%= link_to 'Editar perfil', edit_applicant_profile_path(applicant_profile) %></p>
        <p><%= link_to 'Deletar perfil', applicant_profile_path(applicant_profile), method: :delete %></p>
        <br>
        <% end %>
    <% end %>

    <h4 style="background-color:rgb(241, 255, 183);" ><strong>Proposta recebida</strong></h4>

        <% @head_proposals.each do |proposal| %>
            <p>Título: <%= proposal.title %></p>
            <p>Mensagem: <%= proposal.body %></p>
        <% end %>  
    <br>
    <h4 style="background-color:rgb(241, 255, 183);" ><strong>Comentário recebido</strong></h4>
    
        <% @head_comments.each do |comment| %>
            <p>Nome: <%= comment.username %></p>
            <p>Mensagem: <%= comment.body %></p>
        <% end %>
    <br>
  <% else %>

    <p>Usuário não autorizado.</p>

  <% end %>

app/views/applicant_profiles/new.html.erb
<h1>Criar perfil</h1>

<%= render partial: 'form', locals: { applicant_profile: @applicant_profile } %>
<p><%= link_to 'Voltar', applicant_profiles_path %></p>

app/views/applicant_profiles/show.html.erb
<h1><%= @applicant_profile.name %></h1>
<dl>
  <dt>Nome social:</dt>
  <dd><%= @applicant_profile.social_name %></dd>
  <dt> Data de aniversário:</dt>
  <dd><%= @applicant_profile.date_of_birth %></dd>
  <dt>Educação:</dt>
  <dd><%= @applicant_profile.education %></dd>
  <dt>Descrição:</dt>
  <dd><%= @applicant_profile.applicant_description %></dd>
  <dt>Experiência:</dt>
  <dd><%= @applicant_profile.experience %></dd>
</dl>
<p><%= link_to 'Voltar', applicant_profiles_path %></p>