config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :jobs
  resources :applicant_profiles
  resources :applies
  resources :head_profiles
 
  resources :proposals do
    resources :comments
  end
  
  resources :head_proposals do
    resources :head_comments
  end

  resources :control_users

end

app/models/head_profile.rb
class HeadProfile < ApplicationRecord
    validates :name, presence: { message: 'não pode ficar em branco' }
    validates :company, presence: { message: 'não pode ficar em branco' }
end

app/controllers/head_profiles_controller.rb
class HeadProfilesController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @users = User.all
      @comments = Comment.all
      @proposals = Proposal.all
      @head_profiles = HeadProfile.all
    end

    def show
      @head_profile = HeadProfile.find(params[:id])
    end

    def new
      @head_profile = HeadProfile.new
    end

    def create
      @head_profile = HeadProfile.new(head_profile_params)
            
      if @head_profile.save
        redirect_to @head_profile
      else
        flash.now[:alert] = 'Favor preencher todos os campos'  
        render :new 
      end
    end

    def edit
      @head_profile = HeadProfile.find(params[:id])
    end  

    def update
      @head_profile = HeadProfile.find(params[:id])
      @head_profile.update(head_profile_params)
      redirect_to @head_profile
    end

    def destroy
      head_profile = HeadProfile.find(params[:id]) 
      head_profile.destroy 
      redirect_to root_path
    end
    
    private

    def head_profile_params
      params.require(:head_profile).permit(:name, :company)
    end

end

app/views/head_profiles/_form.html.erb
<h2>Perfil</h2>

<%= form_for head_profile do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :company, 'Empresa' %>
      <%= f.text_field :company %>
    </div>
    <%= f.submit 'Enviar' %>
  <% end %>

app/views/head_profiles/edit.html.erb
<%= render partial: 'form', locals: { head_profile: @head_profile } %>
<p><%= link_to 'Voltar', head_profiles_path %></p>

app/views/head_profiles/index.html.erb
<% if current_user.email == 'headhunter@headhunter.com' %>

    <h1>Painel de acesso</h1>

    <% if @head_profiles.empty? %>
        <p>Perfil ainda não cadastrado.</p>
        <p>Para ter acesso aos canditados e vagas, favor cadastrar perfil.</p>
        <p><%= link_to 'Criar perfil', new_head_profile_path %></p>
    <% else %>
        <p><%= link_to 'Acesso ao painel de vagas', jobs_path %></p> 
        <p><%= link_to 'Candidatos cadastrados', applies_path %></p>
        <p><%= link_to 'Fazer proposta', head_proposals_path %></p>
        <p><%= link_to 'Fazer comentário', head_proposals_path %></p>
        <p><h2>Perfil</h2></p>
    <% @head_profiles.each do |head_profile| %>
        <p>Nome: <%= head_profile.name %></p>
        <p>Empresa: <%= head_profile.company %></p>
        <p><%= link_to 'Editar perfil', edit_head_profile_path(head_profile) %></p>
        <p><%= link_to 'Deletar perfil', head_profile_path(head_profile), method: :delete %></p>
        <br>
        <% end %>
    <% end %>

    <h4 style="background-color:rgb(241, 255, 183);" ><strong>Contra-proposta recebida</strong></h4>

        <% @proposals.each do |proposal| %>
            <p>Título: <%= proposal.title %></p>
            <p>Texto: <%= proposal.body %></p>
        <% end %>
    <br>
    <h4 style="background-color:rgb(241, 255, 183);" ><strong>Comentário recebido</strong></h4>

        <% @comments.each do |comment| %>
            <p>Nome: <%= comment.username %></p>
            <p>Texto: <%= comment.body %></p>
        <% end %>
    <br>
<% else %>

        <p>Usuário não autorizado.</p>

<% end %>

app/views/head_profiles/new.html.erb
<h1>Criar perfil</h1>

<%= render partial: 'form', locals: { head_profile: @head_profile } %>
<p><%= link_to 'Voltar', head_profiles_path %></p>

app/views/head_profiles/show.html.erb
<h1><%= @head_profile.name %></h1>
<dl>
  <dt>Empresa:</dt>
  <dd><%= @head_profile.company %></dd>
</dl>

<p><%= link_to 'Voltar', head_profiles_path %></p>