config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :jobs
  resources :applicant_profiles
  resources :applies
  resources :head_profiles
 
  resources :proposals do
    resources :comments
  end
  
  resources :head_proposals do
    resources :head_comments
  end

  resources :control_users

end

app/models/proposal.rb
class Proposal < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6} 
    validates :body, presence: true
    has_many :comments, dependent: :destroy 
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @head_profiles = HeadProfile.all
      @proposals = Proposal.all
    end

    def show
      @proposal = Proposal.find(params[:id])
    end

    def new
      @proposal = Proposal.new
    end

    def create
      @proposal = Proposal.new(proposal_params)
            
      if @proposal.save
        redirect_to @proposal
      else
        flash.now[:alert] = 'Favor preencher todos os campos'  
        render :new 
      end
    end

    def edit
      @proposal = Proposal.find(params[:id])
    end  

    def update
      @proposal = Proposal.find(params[:id])
      @proposal.update(proposal_params)
      redirect_to @proposal
    end

    def destroy
      @proposal = Proposal.find(params[:id])
      @proposal.destroy 
      redirect_to root_path
    end

    private

    def proposal_params
      params.require(:proposal).permit(:title, :body,)
    end

end

app/views/proposals/edit.html.erb
<h1>Editar Proposta</h1>

<%= form_for :proposal, url: proposal_path(@proposal), method: :patch do |f| %>
    <div>
      <%= f.label :title, 'Titulo' %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :body, 'Texto' %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Enviar' %>
<% end %>

<p><%= link_to 'Voltar', proposals_path %></p>

app/views/proposals/index.html.erb
<h1>Proposta</h1>

<% if @head_profiles.empty? %>
  <%= 'Não exitem HeadHunters cadastrados.' %>
<% else %>
    <% @proposals.each do |proposal| %>
      <h3><%= proposal.title %></h3>
      <p><%= proposal.body %></p>
      <p><%= link_to 'Deletar proposta', proposal_path(proposal), method: :delete %></p>
      <p><%= link_to 'Fazer Comentário', proposal_path(proposal) %></p>
    <% end %>
  <p><%= link_to 'Criar Proposta', new_proposal_path %></p>
<% end %>

<p><%= link_to 'Voltar', root_path %></p>

app/views/proposals/new.html.erb
<h1>Adicionar Proposta</h1>

<%= form_for :proposal, url: proposals_path do |f| %>
    <div>
      <%= f.label :title, 'Nome do candidato' %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :body, 'Texto' %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Enviar' %>
<% end %>

<p><%= link_to 'Voltar', proposals_path %></p>

app/views/proposals/show.html.erb
<h2><%= @proposal.title %></h2>
<p><%= @proposal.body %></p>

<p><%= link_to 'Editar', edit_proposal_path(@proposal) %></p>
<p><%= link_to 'Deletar', proposal_path(@proposal), method: :delete,
                            data: {confirm: 'Tem certeza?'}  %></p>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>

<p><%= link_to 'Voltar', applicant_profiles_path %>