config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :jobs
  resources :applicant_profiles
  resources :applies
  resources :head_profiles
 
  resources :proposals do
    resources :comments
  end
  
  resources :head_proposals do
    resources :head_comments
  end

  resources :control_users

end

app/models/head_proposal.rb
class HeadProposal < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6} 
    validates :body, presence: true
    has_many :head_comments, dependent: :destroy 
end

app/controllers/head_proposals_controller.rb
class HeadProposalsController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @applicant_profiles = ApplicantProfile.all
      @head_proposals = HeadProposal.all
    end

    def show
      @head_proposal = HeadProposal.find(params[:id])
    end

    def new
      @head_proposal = HeadProposal.new
    end

    def create
      @head_proposal = HeadProposal.new(head_proposal_params)
            
      if @head_proposal.save
        redirect_to @head_proposal
      else
        flash.now[:alert] = 'Favor preencher todos os campos'  
        render :new 
      end
    end

    def edit
      @head_proposal = HeadProposal.find(params[:id])
    end  

    def update
      @head_proposal = HeadProposal.find(params[:id])
      @head_proposal.update(head_proposal_params)
      redirect_to @proposal
    end

    def destroy
      @head_proposal = HeadProposal.find(params[:id])
      @head_proposal.destroy 
      redirect_to root_path
    end

    private

    def head_proposal_params
      params.require(:head_proposal).permit(:title, :body,)
    end

end

app/views/head_proposals/edit.html.erb
<h1>Editar Proposta Headhunter</h1>

<%= form_for :head_proposal, url: head_proposal_path(@head_proposal), method: :patch do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Titulo' %>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :body, 'Texto' %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Enviar' %>
<% end %>

<p><%= link_to 'Voltar', head_proposals_path %></p>

app/views/head_proposals/index.html.erb
<h1>Proposta Headhunter</h1>

<% if @applicant_profiles.empty? %>
  <%= 'Não existem candidatos cadastrados' %>
<% else %>
    <% @head_proposals.each do |proposal| %>
      <h3><%= proposal.title %></h3>
      <p><%= proposal.body %></p>
      <p><%= link_to 'Deletar proposta', head_proposal_path(proposal), method: :delete %></p>
      <p><%= link_to 'Fazer Comentário', head_proposal_path(proposal) %></p>
      <% end %>
    <p><%= link_to 'Criar Proposta', new_head_proposal_path %></p>
<% end %>

app/views/head_proposals/new.html.erb
<h1>Adicionar Proposta HeadHunter</h1>

<%= form_for :head_proposal, url: head_proposals_path do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Título' %>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :body, 'Texto' %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Enviar' %>
<% end %>

<p><%= link_to 'Voltar', head_proposals_path %></p>

app/views/head_proposals/show.html.erb
<h2><%= @head_proposal.title %></h2>
<p><%= @head_proposal.body %></p>

<p><%= link_to 'Editar', edit_head_proposal_path(@head_proposal) %></p>
<p><%= link_to 'Deletar', head_proposal_path(@head_proposal), method: :delete,
                            data: {confirm: 'Tem certeza?'}  %></p>

<%= render 'head_comments/comments' %>
<%= render 'head_comments/form' %>

<p><%= link_to 'Voltar', head_profiles_path %>